function Hd = getFilter
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and DSP System Toolbox 9.10.
% Generated on: 17-Mar-2021 10:29:51

Fpass = 450;   % Passband Frequency
Fstop = 480;   % Stopband Frequency
Apass = 1;     % Passband Ripple (dB)
Astop = 3000;  % Stopband Attenuation (dB)
Fs    = 2000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'MatchExactly', 'passband', ...
    'SystemObject', true);


